### ISSUE TITLE
Typo in Flutter's documentation code which leads to error

### ISSUE THREAD

**Issue by lucasuracosta** [singular-labs/Singular-Flutter-SDK#40]
In the [section concerning Flutter deep links](https://support.singular.net/hc/en-us/articles/4408894547227-Singular-SDK-Integration-for-Flutter#Implementing_Deep_Links) the kotlin code says:

`import android.content.intent;`

When trying to use that one the following error is thrown: `Unresolved reference: Intent`.

The reason is because the import should be:

`import android.content.Intent;` (Capital "i" on intent)

A subtle detail which was tricky to find out. I hope it helps for new users once you update it!

Thanks!

**Comment by shefdanny** [comment]
fixed. Thank you.
