### ISSUE TITLE
Does not work with android

### ISSUE THREAD

**Issue by TurkiTAK** [singular-labs/Singular-Flutter-SDK#47]
iOS worked fine. But android compliation produces the following error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':singular_flutter_sdk'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by shefdanny** [comment]
Thanks for notifying us regarding the issue. 
Fixed with released version 1.4.1
