### ISSUE TITLE
Error - Using insecure protocols with repositories, without explicit opt-in, is unsupported while integrating flutter as module. 

### ISSUE THREAD

**Issue by happysingh23828** [singular-labs/Singular-Flutter-SDK#5]
We have used flutter as module and We have integrated **singular flutter 1.0.0** successfully. while integrating module gradle is not able to build.

<img width="1273" alt="Screenshot 2021-12-17 at 2 05 12 PM" src="https://user-images.githubusercontent.com/26920113/146515012-af4c2770-b1d7-41b7-a9d9-f56b92fe74d0.png">

`FAILURE: Build failed with an exception.

```
* What went wrong:
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven5(http://maven.singular.net/)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.0.2/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 
```

**Comment by happysingh23828** [comment]
@friedran @haxorcize @yuvalcar @flow3d , if you released this issue, pls try to acknowledge here also. Will be helpful = for the next time.

**Comment by jzviaginSingular** [comment]
gladle plug in can be downgraded to < 7

**Comment by omribaraksingular** [comment]
Hi @happysingh23828. 
We have updated our flutter SDK.
You can use our latest version and the problem is solved.

**Comment by happysingh23828** [comment]
Thanks @omribaraksingular, I'll check this. 👍 .

closing the thread.
