### ISSUE TITLE
Android namespace issue

### ISSUE THREAD

**Issue by Oladips** [singular-labs/Singular-Flutter-SDK#50]
Incorrect package="com.singular.flutter_sdk" found in source AndroidManifest.xml: /Users/****/.pub-cache/hosted/pub.dev/singular_flutter_sdk-1.3.2/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.

**Comment by shefdanny** [comment]
Thanks for notifying us regarding the issue. 
Fixed with released version 1.4.1
