### ISSUE TITLE
namespace error for android

### ISSUE THREAD

**Issue by MohamedAbdolraheem** [singular-labs/Singular-Flutter-SDK#55]
the package does not work for android 
it throws namespace error (Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported
Recommendation: remove package="com.singular.flutter_sdk" from the source AndroidManifest.xml).

**Comment by shefdanny** [comment]
Thanks for notifying us regarding the issue. 
Fixed with released version 1.4.1
